spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yxl
    username: root
    password: 19951230
  freemarker:
    check-template-location: false
    #禁用缓存
    cache: false
  mvc:
    static-path-pattern: /static/**
mybatis:
  mapper-locations: cn/aptech/mapper/*.xml
  type-aliases-package: cn.aptech.pojo